# Generated by Django 4.2.8 on 2024-05-30 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_category', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('descripcion_producto', models.CharField(max_length=255)),
                ('precio_producto', models.IntegerField(max_length=15)),
                ('stock_producto', models.IntegerField(default=0, max_length=15)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado_pedido', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesado', 'Procesado'), ('Enviado', 'Entregado'), ('Entregado', 'Entregado')], default='Pendiente', max_length=255)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
