# Generated by Django 4.2.8 on 2024-05-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_producto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_producto',
            field=models.IntegerField(default=0),
        ),
    ]
